# Generated by Django 5.1.5 on 2025-02-03 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, default='default_profile_pic.jpg', null=True, upload_to='profile_pictures/')),
                ('bio', models.TextField(default='New Member')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('experience_level', models.CharField(default='Beginner', max_length=50)),
                ('membership_complete', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
