# Generated by Django 5.1.5 on 2025-02-03 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='experience_level',
            new_name='rank',
        ),
    ]
