# Generated by Django 5.1.5 on 2025-02-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_experience_level_profile_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(default='Vacant', max_length=50),
        ),
    ]
